# Generated by Django 5.2 on 2025-04-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_preferred_age_max_profile_preferred_age_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='image',
        ),
        migrations.AlterField(
            model_name='letter',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='letters/pdf/'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='letters/images/')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.letter')),
            ],
        ),
    ]
