# Generated by Django 5.2 on 2025-05-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connection_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='letterlike',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='letterlike',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letterlike',
            name='to_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='core.letter'),
        ),
    ]
