# Generated by Django 5.2 on 2025-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='only_same_city',
            field=models.BooleanField(default=False),
        ),
    ]
