# Generated by Django 5.2 on 2025-11-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_profile_limit_to_event_pool_alter_letter_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
    ]
